---
title: "Other Resources"
---

## Resource Collections and Bibliographies

- The 2021 [MSRI Workshop on Mathematics and Racial Justice](https://www.msri.org/workshops/1012) collected a [list of resources](https://docs.google.com/document/d/1-40eCiJdlOIxDWnALv-kqO5-0c5NH1M857-_kTj-GeE/edit?usp=sharing) on mathematics and racial justice, including books, journal articles, organizations, and data sets. They also published [a compendium](http://library.msri.org/msri/Math-and-Racial-Justice.pdf) of their work. 
- [Allison Miller](https://sites.google.com/view/anmiller/) (Swarthmore College) maintains an annotated list of [resources on ethics in mathematics](https://docs.google.com/document/d/1P4xAUa9qfEbeCjurGOdJH3dW2JErVRJZ1K9DLAT8uYE/edit). 

## Books and Articles

- [*Weapons of Math Destruction*](https://bookshop.org/books/weapons-of-math-destruction-how-big-data-increases-inequality-and-threatens-democracy/9780553418835) by Cathy O'Neil.
- [*Algorithms of Oppression: How Search Engines Reinforce Racism*](https://bookshop.org/books/algorithms-of-oppression-how-search-engines-reinforce-racism/9781479837243) by Safiya Umoja Noble.
- [*Automating Inequality*](https://bookshop.org/books/automating-inequality-how-high-tech-tools-profile-police-and-punish-the-poor/9781250215789) by Virginia Eubanks.
- [*Invisible Women: Data Bias in a World Designed for Men*](https://bookshop.org/books/invisible-women-data-bias-in-a-world-designed-for-men/9781419735219) by Caroline Criado Perez. 
- [A People's Guide to Finding Algorithmic Bias](https://www.criticalracedigitalstudies.com/peoplesguide) by the [Center for Critical Race and Digital Studies](https://www.criticalracedigitalstudies.com) affiliated with [NYU's Institute of Human Development and Social Change](https://steinhardt.nyu.edu/ihdsc). 

## Other Tools

- The [Academic Wheel of Privilege](https://science.nasa.gov/files/science-pink/s3fs-public/styles/background_image_file_size/public/thumbnails/image/academic%20wheel%20of%20privilege.JPG?itok=Jp0QfgtW) by Dr. Flavio Azevedo as described in [this interview](https://science.nasa.gov/open-science/transform-to-open-science/stories/dr-flavio-azevedo). 



